### ISSUE TITLE
Connecting to a telnet server from Windows

### ISSUE THREAD

**Issue by oleh-zayats** [swisspol/GCDTelnetServer#1]
Hi Pierre!

I'm currently working on an iOS port of iPerf network bandwidth measurement tool. Using your library which works like a charm on OS X, but having an issue on Windows. 
I'm successfully connecting to my iOS device from windows command line, but then it doesn't send any commands, just freezes. Do you have any ideas why this is happening?
Tested on win7, winXP, checked firewall - same thing everywhere...

thank you in advance,
Oleh

**Comment by swisspol** [comment]
No idea, sorry. Did you trace what is happening on the GCDTelnetServer side?

**Comment by oleh-zayats** [comment]
Hey Pierre,
the problem was that when I was hitting 'Enter' on windows GCDTelnetConnection class did not process the 'line feed' symbol (0x0A), so command line was waiting for the 'return carriage' (0x0D). I've added a check in 'processRawInput:' method and now everything works fine!

**Comment by swisspol** [comment]
Ah good find! And thanks for the update. Please send a PR if you get a chance.
